[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "cd backend && npm ci",
  "cd frontend && npm ci --include=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r frontend/build/* backend/public/"
]

[start]
cmd = "cd backend && npm start"
